frontend/urls.py
from django.urls import path, include
from .views import HomePageView, DeezerRequestView, ArtistListView, ArtistDetailView, AlbumListView, AlbumDetailView, SongListView, SongDetailView, ArtistUpdateView, SongUpdateView, search_view

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('create/', DeezerRequestView.as_view(), name='create_from_deezer'),
    path('artist/', ArtistListView.as_view(), name="artist_list"),
    path('album/', AlbumListView.as_view(), name="album_list"),
    path('song/', SongListView.as_view(), name="song_list"),
    path('artist/<int:pk>/', ArtistDetailView.as_view(), name='artist_detail'),
    path('album/<int:pk>/', AlbumDetailView.as_view(), name='album_detail'),
    path('song/<int:pk>/', SongDetailView.as_view(), name='song_detail'),
    path('artist/update/<int:pk>/',
         ArtistUpdateView.as_view(), name='artist_update'),
    path('song/update/<int:pk>/',
         SongUpdateView.as_view(), name='song_update'),
    path('search/', search_view, name='search_view'),
]

m_collection/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('', include('users.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import UserCollectionDetailView, UserRegisterView, UserLoginView, UserLogoutView, add_album_to_collection, remove_album_from_collection, add_song_to_collection, remove_song_from_collection, add_artist_to_collection, remove_artist_from_collection, UserCollectionArtistView, UserCollectionAlbumView, UserCollectionSongView

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('collections/<int:pk>/', UserCollectionDetailView.as_view(), name='user_collection_detail'),
    path('add_album_to_collection/<int:album_id>/', add_album_to_collection, name='add_album_to_collection'),
    path('remove_album_from_collection/<int:album_id>/', remove_album_from_collection, name='remove_album_from_collection'),
    path('collection/add/song/<int:song_id>/', add_song_to_collection, name='add_song_to_collection'),
    path('collection/remove/song/<int:song_id>/', remove_song_from_collection, name='remove_song_from_collection'),
    path('collection/add/artist/<int:artist_id>/', add_artist_to_collection, name='add_artist_to_collection'),
    path('collection/remove/artist/<int:artist_id>/', remove_artist_from_collection, name='remove_artist_from_collection'),
    path('collections/artist/', UserCollectionArtistView.as_view(), name='user_collection_artist_list'),
    path('collections/album/', UserCollectionAlbumView.as_view(), name='user_collection_album_list'),
    path('collections/song/', UserCollectionSongView.as_view(), name='user_collection_song_list'),
    ]

frontend/models.py
from django.db import models



class Artist(models.Model):
    """
    Model to store information about music artists.
    """
    name = models.CharField(max_length=100, unique=True,
                            help_text="Name of the artist")
    photo_url = models.URLField(
        max_length=200, null=True, help_text="URL of the artist's photo")
    photo = models.ImageField(null=True, blank=True,
                              upload_to='artist_photos/', help_text="Artist's photo")
    review = models.TextField(help_text="Review of the artist")
    youtube_link = models.URLField(
        help_text="Artist's YouTube link", null=True, blank=True)
    deezer_link = models.URLField(help_text="Artist's Deezer link", null=True)
    instagram_link = models.URLField(
        help_text="Artist's Instagram link", null=True, blank=True)

    def __str__(self):
        """
        Method to get the string representation of the artist.
        """
        return self.name


class Album(models.Model):
    """
    Model to store information about music albums.
    """
    title = models.CharField(max_length=100, help_text="Title of the album")
    artist = models.ForeignKey(
        Artist, on_delete=models.CASCADE, related_name='albums',
        help_text="Artist of the album"
    )

    year = models.PositiveIntegerField(help_text="Release year of the album")
    cover_url = models.URLField(
        max_length=200, null=True, help_text="URL of the album cover")
    main_cover = models.ImageField(
        upload_to='album_covers/', help_text="Main cover of the album", null=True, blank=True)
    tracklist = models.JSONField(
        help_text="List of songs in the album in JSON format")
    comments = models.TextField(
        help_text="Additional comments about the album")
    deezer_album_link = models.URLField(
        help_text="Albums's Deezer link", null=True)

    def __str__(self):
        """
        Method to get the string representation of the album.
        """
        return f'{self.title}'


class Song(models.Model):
    """
    Model to store information about songs in albums.
    """
    song = models.CharField(max_length=100, help_text="Title of the song")
    album = models.ForeignKey(
        Album, on_delete=models.CASCADE, help_text="Album to which the song belongs"
    )
    artist = models.ForeignKey(
        Artist, on_delete=models.CASCADE, help_text="Artist of the song"
    )
    lyrics = models.TextField(help_text="Lyrics of the song")
    youtube_link = models.URLField(
        help_text="YouTube link of the song", null=True, blank=True)
    deezer_link = models.URLField(
        help_text="Deezer link of the song", null=True)

    def __str__(self):
        """
        Method to get the string representation of the song.
        """
        return f"{self.song}"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from frontend.models import Album, Song, Artist  

class User(AbstractUser):
    """
    Custom user model extending Django's AbstractUser.
    """
    
    def __str__(self):
        return self.username


class UserCollection(models.Model):
    """
    Model to represent a user's music collection.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  
    albums = models.ManyToManyField(Album, blank=True, related_name='user_collections')
    songs = models.ManyToManyField(Song, blank=True, related_name='user_collections')
    artists = models.ManyToManyField(Artist, blank=True, related_name='user_collections')

    def __str__(self):
        return f"{self.user.username}'s collection"

frontend/forms.py
from django import forms
from .models import Artist, Song
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field


class ArtistUpdateForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ['review', 'instagram_link', 'youtube_link']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Field('review', css_class='form-control mb-3'),
            Field('instagram_link', css_class='form-control bg-dark text-light mt-2'),
            Field('youtube_link', css_class='form-control bg-dark text-light mt-2'),
        )


class SongUpdateForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['lyrics', 'youtube_link']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Field('lyrics', css_class='form-control mb-3'),
            Field('youtube_link', css_class='form-control bg-dark text-light mt-2'),
        )


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)

frontend/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.db.models import Count,Q
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, TemplateView, DetailView
from django.views.generic.edit import UpdateView
from .utils.deezer_utils import fetch_album_info_from_deezer
from .models import Artist, Album, Song
from .utils.lyrics import get_lyrics
from .forms import SearchForm


class DeezerRequestView(TemplateView):
    """
    View for fetching album information from Deezer.
    """
    template_name = "create_from_deezer.html"

    def get_context_data(self, **kwargs):
        """
        Get context data for the template.

        Returns:
            dict: Context data for the template.
        """
        context = super().get_context_data(**kwargs)
        album_id = self.request.GET.get('album_id')

        if album_id:
            album = fetch_album_info_from_deezer(album_id)
            if album:
                context['album'] = album
                # Iterate through songs in the album
                for song in album.song_set.all():
                    # Fetch lyrics for the song
                    lyrics = get_lyrics(song.artist.name, song.song)
                    if lyrics:
                        # Assign lyrics to the song
                        song.lyrics = lyrics
                        # Save the updated song object
                        song.save()
                    else:
                        song.lyrics = "Lyrics not found for this song."
            else:
                # Handle the case when the album is not found
                context['error_message'] = "Album not found on Deezer."
        return context

    def dispatch(self, request, *args, **kwargs):
        """
        Dispatch method to handle the request.

        Args:
            request: HTTP request object.
            args: Additional arguments.
            kwargs: Additional keyword arguments.

        Returns:
            HttpResponse: HTTP response.

        Notes:
            Checks if album_id is present in the request. If not, continues without redirection.
        """
        # Check if album_id is present in the request
        album_id = self.request.GET.get('album_id')
        if not album_id:
            # If album_id is not present, continue without redirection
            return super().dispatch(request, *args, **kwargs)

        return super().dispatch(request, *args, **kwargs)


class HomePageView(TemplateView):
    template_name = "home.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        random_albums = Album.objects.order_by('?')[:3]

        context['random_albums'] = random_albums
        return context


class ArtistListView(ListView):
    model = Artist
    template_name = 'artist_list.html'
    context_object_name = 'artists'
    ordering = ['name']
    paginate_by = 24  

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        artists_by_album_count = Artist.objects.annotate(
            num_albums=Count('albums')).order_by('-num_albums')
        context['artists_by_album_count'] = artists_by_album_count

        return context



class ArtistDetailView(DetailView):
    model = Artist
    template_name = 'artist_detail.html'
    context_object_name = 'artist'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        artist = self.object
        albums = Album.objects.filter(song__artist=artist).distinct()
        context['albums'] = albums
        return context


class AlbumListView(ListView):
    model = Album
    template_name = 'album_list.html'
    context_object_name = 'albums'
    ordering = ['title']  
    paginate_by = 24  

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        albums_by_year = Album.objects.annotate(
            num_years=Count('year')).order_by('-year')
        context['albums_by_year'] = albums_by_year

        return context


class AlbumDetailView(DetailView):
    model = Album
    template_name = 'album_detail.html'
    context_object_name = 'album'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        album = self.object
        context['songs'] = album.song_set.all()
        context['artist_detail_url'] = reverse(
            'artist_detail', kwargs={'pk': album.artist.pk})
        return context


class SongListView(ListView):
    model = Song
    template_name = 'song_list.html'
    context_object_name = 'songs'
    ordering = ['song']
    paginate_by = 20  

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        artist_list = context[self.context_object_name]
        artists_with_most_songs = Artist.objects.annotate(
            num_songs=Count('song')).order_by('-num_songs')[:15]  
        context['artists_with_most_songs'] = artists_with_most_songs
        paginator = Paginator(artist_list, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['songs'] = page_obj
        return context


class SongDetailView(DetailView):
    model = Song
    template_name = 'song_detail.html'
    context_object_name = 'song'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        song = self.object
        album_cover_url = song.album.cover_url
        artist_photo_url = song.artist.photo_url
        context['artist_detail_url'] = reverse(
            'artist_detail', kwargs={'pk': song.artist.pk})
        context['album_detail_url'] = reverse(
            'album_detail', kwargs={'pk': song.album.pk})
        context['album_cover_url'] = album_cover_url
        context['artist_photo_url'] = artist_photo_url
        return context


class ArtistUpdateView(UpdateView):
    model = Artist
    fields = ['review', 'instagram_link', 'youtube_link']
    template_name = 'artist_update.html'
    
    def get_success_url(self):
        return reverse('artist_detail', kwargs={'pk': self.object.pk})


class SongUpdateView(UpdateView):
    model = Song
    fields = ['lyrics', 'youtube_link']
    template_name = 'song_update.html'
    success_url = reverse_lazy('song_list')
    
    def get_success_url(self):
        return reverse('song_detail', kwargs={'pk': self.object.pk})
    

def search_view(request):
    form = SearchForm(request.GET)
    results = []
    
    if form.is_valid():
        query = form.cleaned_data['query']
        
        results = {
            'songs': Song.objects.filter(Q(song__icontains=query)),
            'albums': Album.objects.filter(Q(title__icontains=query)),
            'artists': Artist.objects.filter(Q(name__icontains=query))
        }
    
    return render(request, 'search_results.html', {'form': form, 'results': results})

frontend/templates/user_collection/album_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container py-4">
  <h2 class="text-light text-center my-4">
    {% with user_collection=user.usercollection_set.first %}
  <a class="link-light text-decoration-none" href="{% url 'user_collection_detail' user_collection.id %}">{{ object.user.username }}'s Collection</a>
  {% endwith %}
     - Albums</h2>
      <div class="row">
        <div class="col d-flex flex-wrap justify-content-center">
        {% for album in object.albums.all %}  
        <div class="card bg-warning me-3 my-2" style="width: 12rem;">
          <a href="{% url 'album_detail' album.pk %}">
            <img
              src="{{ album.cover_url }}"
              class="card-img-top"
              alt="{{ album.title }}"
            />
          </a>
          <div class="card-body">
            <a
              class="link-dark text-decoration-none"
              href="{% url 'album_detail' album.pk %}"
            >
              <h6 class="card-title">{{ album.title }} - {{ album.artist }}</h6>
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
      
      <!-- Pages -->
      <div class="d-flex justify-content-center">
        {% if is_paginated %}
      <div class="pagination" style="text-align: center; margin-top: 20px;">
        {% if page_obj.has_previous %}
        <a href="?page=1" style="margin-right: 10px" class="link-warning">&laquo; First</a>
        <a
          href="?page={{ page_obj.previous_page_number }}"
          style="margin-right: 10px"
          class="link-warning"
        >
          Previous
        </a>
        {% endif %}

        <span class="current-page" style="margin-right: 10px">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a
          href="?page={{ page_obj.next_page_number }}"
          class="link-warning"
          style="margin-right: 10px"
        >
          Next
        </a>
        <a
          href="?page={{ page_obj.paginator.num_pages }}"
          class="link-warning"
          style="margin-right: 10px"
        >
          Last &raquo;
        </a>
        {% endif %}
      </div>

      </div>
      
      {% endif %}
    </div>
    
  </div>
</div>

{% endblock content %}

frontend/templates/user_collection/artist_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container py-4">
  
      <h2 class="text-light text-center my-4">
        {% with user_collection=user.usercollection_set.first %}
      <a class="link-light text-decoration-none" href="{% url 'user_collection_detail' user_collection.id %}">{{ object.user.username }}'s Collection</a>
      {% endwith %}
         - Artists</h2>
      
      <div class="row">
        <div class="col d-flex flex-wrap justify-content-center">
        {% for artist in object.artists.all %}
          <div class="card bg-warning me-3 my-2" style="width: 12rem;">
            <a href="{% url 'artist_detail' artist.pk %}">
              <img
                src="{{ artist.photo_url }}"
                class="card-img-top"
                alt="{{ artist.name }}"
              />
            </a>
            <div class="card-body">
              <a
                class="link-dark text-decoration-none"
                href="{% url 'artist_detail' artist.pk %}"
              >
                <h6 class="card-title">{{ artist.name }}</h6>
              </a>
            </div>
          </div>
        {% endfor %}
      </div>
      <!-- Paginate section -->
      <div class="d-flex justify-content-center">
        {% if is_paginated %}
        <div class="pagination mt-3">
          {% if page_obj.has_previous %}
            <a href="?page=1" style="margin-right: 10px" class="link-warning">&laquo; First</a>
            <a
              href="?page={{ page_obj.previous_page_number }}"
              style="margin-right: 10px"
              class="link-warning"
            >
              Previous
            </a>
          {% endif %}
          <span class="current-page" style="margin-right: 10px">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>
          {% if page_obj.has_next %}
            <a
              href="?page={{ page_obj.next_page_number }}"
              style="margin-right: 10px"
              class="link-warning"
            >
              Next
            </a>
            <a
              href="?page={{ page_obj.paginator.num_pages }}"
              style="margin-right: 10px"
              class="link-warning"
            >
              Last &raquo;
            </a>
          {% endif %}
        </div>

      </div>
      
      {% endif %}
    </div>
    
    
  </div>
</div>
{% endblock %}

frontend/templates/user_collection/song_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container py-4">
  <h2 class="text-light text-center my-4">
    {% with user_collection=user.usercollection_set.first %}
  <a class="link-light text-decoration-none" href="{% url 'user_collection_detail' user_collection.id %}">{{ object.user.username }}'s Collection</a>
  {% endwith %}
     - Songs</h2>
  <div class="row">
    <div class="col d-flex flex-wrap justify-content-center">
      <table class="table table-dark w-auto">
        <thead>
          <tr class="text-dark"> 
            <th class="bg-warning text-dark">Title</th>
            <th class="bg-warning text-dark">Album</th>
            <th class="bg-warning text-dark">Artist</th>
          </tr>
        </thead>
        <tbody>
          {% for song in object.songs.all %}
          <tr>
            <td>
              <a
                class="link-light text-decoration-none"
                href="{% url 'song_detail' song.pk %}"
              >
                <p>{{ song.song }}</p>
              </a>
            </td>
            <td>
              <a
                class="link-light text-decoration-none"
                href="{% url 'album_detail' song.album.pk %}"
              >
                <p>{{ song.album }}</p>
              </a>
            </td>
            <td>
              <a
                class="link-light text-decoration-none"
                href="{% url 'artist_detail' song.artist.pk %}"
              >
                <p>{{ song.artist }}</p>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <div class="d-flex justify-content-center">
    {% if is_paginated %}
    <div class="pagination">
      {% if page_obj.has_previous %}
      <a href="?page=1" class="link-warning" style="margin-right: 10px;">&laquo; First</a>
      <a
        href="?page={{ page_obj.previous_page_number }}"
        class="link-warning"
        style="margin-right: 10px;"
      >
        Previous
      </a>
      {% endif %}

      <span class="current-page" style="margin-right: 10px;">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
      <a
        href="?page={{ page_obj.next_page_number }}"
        class="link-warning"
        style="margin-right: 10px;"
      >
        Next
      </a>
      <a
        href="?page={{ page_obj.paginator.num_pages }}"
        class="link-warning"
        style="margin-right: 10px;"
      >
        Last &raquo;
      </a>
      {% endif %}
    </div>
    {% endif %}
  </div>
</div>

{% endblock %}